### ISSUE TITLE
Does not compile files from ignored directory - roots v3

### ISSUE THREAD

**Issue by chasevida** [carrot/roots-js-pipeline#7]
The `js-pipeline` extension does not pipe files from any directories that have been added to the ignore list in `app.coffee` such as `bower_components`. This may be intentional but seems like what I'm trying to achieve would be a fairly standard use case.

In the below example the compiled `js/build.js` is empty. When I remove `bower_components` from the list of ignores it compiles correctly.

```
module.exports =
  ignores: [
    'bower.json',
    'bower_components/**',
  ]

  extensions: [
    pipeline(files: [
      'bower_components/somelib/somefile.js'
    ], out: 'js/build.js')
  ]
```

**Comment by ryanjbonnell** [comment]
I don't know if this behavior has changed [in the last ~1.5 years circa 2014] since this issue was created, but I'm using Roots 4.x and don't seem to have this problem.

Here's a snippet of my **app.coffee**:

```
js_pipeline = require 'js-pipeline'

module.exports =
  ignores: [
    'bower.json',
    'bower_components',
  ]

  extensions: [
    ...
    js_pipeline
      files: [
        'bower_components/jquery/dist/jquery.min.js'
        'bower_components/jquery-cycle2/build/jquery.cycle2.min.js'
      ]
  ]
```

I tested this against a new example project in Roots v4.0.1 and libraries I've installed via Bower (and are ignored in module.exports) are included in the compiled output.

For example, using the above configuration and the js-pipeline function in **layout.jade**:

```
!= js('/')
```

Will output the following compiled HTML:

```
<script src='/bower_components/jquery/dist/jquery.min.js'></script>
<script src='/bower_components/jquery-cycle2/build/jquery.cycle2.min.js'></script>
```

This even works when having roots-js-pipeline concatenate and minify source files, which is especially valuable for use in **app.production.coffee**:

```
js_pipeline
  hash: true
  manifest: 'assets/js/_manifest.yml'
  minify: true
  out: 'assets/js/build.js'
```

Which results in:

`<script src='/assets/js/build.27f08aa7d360d835eef3fc91bc495ddf.js'></script>`

**Comment by chasevida** [comment]
Thanks @ryanjbonnell, unfortunately I haven't had the pleasure of much time to continue developing the extensions this issue was raised in connection with... as such I don't recall much about it off the top of my head. Since it's been 1.5 years, as you say, perhaps it's best to close this issue now. Thanks again.
